server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/flower_delivery?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 47.121.208.210
    port: 6379
    password: 123456
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.flower.entity

jwt:
  secret: your_jwt_secret_key
  expiration: 3600000 # 1 hour in milliseconds

# Swagger Configuration (可选)
springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs

# Nginx 配置假设在生产环境中配置，这里不详细展开

